name: piranha-updated
channels:
  - conda-forge
  - bioconda
  - defaults
  - nanoporetech 
dependencies:
  - python
  - biopython
  - bcftools=1.23
  - coreutils=9.5
  - flopp=0.2.0
  - freebayes=1.3.6
  - iqtree>=3.0
  - cov-ert::jclusterfunk>=0.0.25
  - mafft
  - medaka=2.2.0
  - minimap2>=2.16
  - rasusa=0.7.1
  - samtools=1.20
  - snakemake-minimal>=9.9.0
  - tabix=1.11
